---
version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - memos:/var/opt/memos
    ports:
      - 5230:5230
volumes:
  memos:
    driver_opts:
      type: "nfs"
      o: "addr=10.32.25.118,nolock,rw,soft,nfsvers=4"
      device: ":/mnt/prox-pool/Coolnow/docker/memos"